config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    member do
      get 'analyze', to: 'articles#count_comments'
      get 'count_comments_rating', to: 'articles#analyze_comments'
    end
    resources :comments, only: [:index, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :url, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy count_comments set_article_number_of_comments analyze_comments]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.title = ArticleAnalyzer.article_name(@article.url)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /articles/1 or /articles/1.json
  def count_comments
    comments_count = ArticleAnalyzer.count_comments(@article)

    respond_to do |format|
      if @article.update(number_of_comments: comments_count)
        format.html { redirect_to article_url(@article) }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def analyze_comments
    ArticleAnalyzer.analyze_comments(@article)
    redirect_to article_url(@article)

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :url, :number_of_comments)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article

  def index
    @comments = Article.find(params[:article_id]).comments
  end

  def create
    ArticleAnalyzer.get_comments(@article)
    redirect_to article_url(@article), notice: "Comments were successfully fetched."
  end

  def destroy
    @comments.destroy
  end

  private

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:comment_text)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Url of article:</strong>
    <%= article.url %>
  </p>

</div>

app/views/articles/_form.html.erb
<div class="container">
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form_with(model: article) do |form| %>
    <div class="row">
      <div class="col-md-6">
        <div class="input-group mb-3">
          <%= form.text_field :url, class: 'form-control', placeholder: 'Enter url of article' %>
          <div class="input-group-append">
            <%= form.submit 'Add article', class: 'btn btn-success' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>
<h2><%= link_to "Add article", new_article_path %></h2>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th class="text-center" colspan='2'>Actions</th>
    <th class="text-center">Rating</th>
    <th class="text-center">Number of comments</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><a href="<%= article.url %>" target="_blank"><%= article.url %></a></td>
      <td>
        <%= link_to article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa fa-trash" style="color: rgba(196,0,0,1); font-size: 18px;"></i>
        <% end %>
      </td>
      <td><%= link_to 'Analyze', analyze_article_path(article), class: 'btn btn-success' %></td>
      <td><%= "placeholder" %></td>
      <td class="text-center"><%= article.number_of_comments %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>Analize article</h1>

<%= render "form", article: @article %>

<br>

<h2>
  <%= link_to "Back to articles", articles_path %>
</h2>

app/views/articles/show.html.erb
<h1>Article info</h1>

<p><strong>Title:</strong> <%= @article.title %></p>
<p><strong>Url of article:</strong> <%= @article.url %></p>
<p><strong>Number of comments: </strong><%= @article.number_of_comments %></p>

<div>
  <strong><%= link_to 'Count comments', analyze_article_path(@article) %></strong> |
  <%= link_to "Get comments", article_comments_path(@article), data: { "turbo-method": :post } %> |
  <%= link_to "Show table of comments", article_comments_path(@article) %> |
  <%= link_to "Count comments rating", count_comments_rating_article_path(@article) %>
  <p></p>
  <h2><%= link_to "Back to articles", articles_path %> |
      <%= link_to "Add another article", new_article_path %> |
      <%= link_to "Delete this article", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </h2>
</div>

app/views/comments/index.html.erb
<div class="table_of_comments">
  <table><strong>Table of comments</strong>
    <thead>
    <tr>
      <td>Author</td>
      <td>
        <center>Comment</center>
      </td>
      <td>Rating</td>
    </tr>
    </thead>
    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= 'Author' %></td>
        <td><%= comment.comment_text %></td>
        <td><%= comment.rating %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div>
  <h2><%= link_to "Back to article", article_path(@article) %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstTast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sandstone/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= yield %>
    </div>
  </div>
  </body>
</html>